### ISSUE TITLE
community.steamID is missing (undefined) even though logged in.

### ISSUE THREAD

**Issue by goodluckgod** [DoctorMcKay/node-steamcommunity#324] opened 2023-10-19 18:28 UTC
Hello,

First of all, I did not create a topic in the forum because I thought this was a **bug**. I could be wrong, sorry in advance.

I am trying to login to my steam user (bot) with proxies via node-steamcommunity, but sometimes the login function returning without any error and i can use other variables. Sometimes i can login to bot without any error.

Here is the function of login method;

```
const loginToBot = async (bot: ISteamBot) => {
  const proxyUrl = await getBestProxy({
    protocol: EProxyProtocol.HTTP,
  });

  return new Promise<
    Omit<
      ISteamContainer,
      | "tradeOfferManager"
      | "trustScore"
      | "increaseTrustScore"
      | "decreaseTrustScore"
    >
  >((resolve, reject) => {
    const community = new SteamCommunity({
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      // @ts-ignore
      request: proxyUrl
        ? request.defaults({
            proxy: proxyUrl,
          })
        : request,
    });
    community.login(
      {
        accountName: bot.username,
        password: bot.password,
        twoFactorCode: SteamTotp.generateAuthCode(bot.sharedSecret),
      },
      async (err, sessionID, cookies, steamguard, oAuthToken) => {
        if (err) {
          return reject(err);
        }

        if (!community.steamID) {
          // debug
          console.log(err, sessionID, cookies, steamguard, oAuthToken);
          return reject(new AppError("NO_STEAM_ID", `Bot: ${bot.username}`));
        }

        const user = (await new Promise((resolve, reject) => {
          community.getSteamUser(community.steamID, (err, user) => {
            if (err) {
              return reject(err);
            }

            return resolve(user);
          });
        })) as CSteamUser;

        return resolve({
          community,
          cookies,
          sessionID,
          steamguard,
          oAuthToken,
          sharedSecret: bot.sharedSecret,
          identitySecret: bot.identitySecret,
          tradeUrl: bot.tradeUrl,
          _id: bot._id,
          information: {
            steamId: community.steamID.toString(),
            username: bot.username,
            name: user.name,
            avatar: void user.getAvatarURL() || "",
          },
        });
      }
    );
  });
};
```

I am getting "NO_STEAM_ID" in this function and situation

Here is the console output;

![image](https://github.com/DoctorMcKay/node-steamcommunity/assets/42766561/628b644c-b6e5-4761-afd1-4f4f6e21d594)

If the bot cannot logged in why i can't see any error?

Thanks.

**Comment by zyoi** [comment] 2023-10-19 18:58
Check my comment on the other issue

https://github.com/DoctorMcKay/node-steamcommunity/issues/323#issuecomment-1771545192

**Comment by goodluckgod** [comment] 2023-10-19 19:03
> Check my comment on the other issue
> 
> [#323 (comment)](https://github.com/DoctorMcKay/node-steamcommunity/issues/323#issuecomment-1771545192)

I will try soon, thanks so much!

**Comment by DoctorMcKay** [comment] 2023-10-19 23:22
Duplicate of #321

**Closed by DoctorMcKay** 2023-10-19 23:22 UTC
