### ISSUE TITLE
Steamcommunity error.

### ISSUE THREAD

**Issue by Tutyko2016** [DoctorMcKay/node-steamcommunity#122] opened 2016-08-09 07:08 UTC
uncaughtException: TypeError: Cannot read property 'success' of undefined
    at /home/csgobot/node_modules/steamcommunity/components/confirmations.js:133:10
    at SteamCommunity.<anonymous> (/home/csgobot/node_modules/steamcommunity/components/confirmations.js:166:3)
    at Request._callback (/home/csgobot/node_modules/steamcommunity/components/http.js:62:14)
    at Request.self.callback (/home/csgobot/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/csgobot/node_modules/request/request.js:1082:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at Gunzip.<anonymous> (/home/csgobot/node_modules/request/request.js:1009:12)
    at emitNone (events.js:72:20)
    at Gunzip.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

**Comment by Tutyko2016** [comment] 2016-08-09 07:08
Steam community total crash.

You can fix it?

**Comment by Lagg** [comment] 2016-08-09 07:15
I'm having the same issue, perhaps you should close this and post in #121 so  that we can keep information about whatever in god's name Valve has done this time centralized.

**Comment by yuickhahirasawa** [comment] 2016-08-09 08:51
I add before [this](https://github.com/DoctorMcKay/node-steamcommunity/blob/master/components/confirmations.js#L87)

`if(body === undefined) {
    callback(new Error("Undefined body");
    return;
}`

And wait DoctorMcKay fix.

**Comment by Tutyko2016** [comment] 2016-08-09 10:24
yuickhahirasawa: Thanks. and wait Dr.Mckay :)

**Comment by Spartacus2k15** [comment] 2016-08-09 16:26
A similar problem occurs here:

> steamcommunity\classes\CMarketItem.js:116
>                 if(body.success != 1) {
>                        ^
> TypeError: Cannot read property 'success' of undefined
>     at SteamCommunity.<anonymous> (steamcommunity\classes\CMarketItem.js:116:10)
>     at Request._callback (steamcommunity\components\http.js:62:14)
>     at Request.self.callback (steamcommunity\node_modules\request\request.js:200:22)
>     at emitTwo (events.js:87:13)
>     at Request.emit (events.js:172:7)
>     at Request.<anonymous> (steamcommunity\node_modules\request\request.js:1067:10)
>     at emitOne (events.js:82:20)
>     at Request.emit (events.js:169:7)
>     at Gunzip.<anonymous> (steamcommunity\node_modules\request\request.js:988:12)
>     at emitNone (events.js:72:20)
>     at Gunzip.emit (events.js:166:7)

**Comment by Lagg** [comment] 2016-08-09 17:07
There is additionally something causing Error objects from getOffer to have undefined message properties. But this would mean the issue is affecting a ton of steam pages. Great.

**Comment by DoctorMcKay** [comment] 2016-08-09 19:46
Should be fixed in v3.23.2.

**Closed** 2016-08-09 19:45 UTC

**Comment by Tutyko2016** [comment] 2016-08-10 22:50
New bugg:

Error: Callback was already called.
    at null._onTimeout (/home/csgobot/node_modules/steamcommunity/node_modules/async/lib/async.js:43:36)
    at Timer.listOnTimeout (timers.js:92:15)
