### ISSUE TITLE
Error: Not Logged In

### ISSUE THREAD

**Issue by piijt** [DoctorMcKay/node-steamcommunity#323] opened 2023-10-19 12:06 UTC
Getting an error while trying to perform a trade,

this is the error-logs. the bot is displayed as logged in on steam, has been working up untill yesterday evening.

I am using steamUser to login with the logOn method, and use webLogOn when session expires, but it does not seem to be the case

```
Error: Not Logged In
    at SteamCommunity.<anonymous> (C:\Users\peter\Desktop\Stuff\trade-raid\code\APP - NEW NODE\steam-trading-service\node_modules\steam-tradeoffer-manager\lib\classes\TradeOffer.js:345:25)
    at Request._callback (C:\Users\peter\Desktop\Stuff\trade-raid\code\APP - NEW NODE\steam-trading-service\node_modules\steamcommunity\components\http.js:67:15)
    at Request.self.callback (C:\Users\peter\Desktop\Stuff\trade-raid\code\APP - NEW NODE\steam-trading-service\node_modules\request\request.js:185:22)
    at Request.emit (node:events:390:28)
    at Request.<anonymous> (C:\Users\peter\Desktop\Stuff\trade-raid\code\APP - NEW NODE\steam-trading-service\node_modules\request\request.js:1154:10)
    at Request.emit (node:events:390:28)
    at Gunzip.<anonymous> (C:\Users\peter\Desktop\Stuff\trade-raid\code\APP - NEW NODE\steam-trading-service\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (node:events:509:28)
    at Gunzip.emit (node:events:390:28)
    at endReadableNT (node:internal/streams/readable:1343:12)
```

**Comment by piijt** [comment] 2023-10-19 17:18
any reason why this would not trigger after calling client.logOn() ?

**Comment by zyoi** [comment] 2023-10-19 18:57
I was try to solve it myself for 3 hourse until I read previous messages and replaced authentication with steam-user. community.login does not work anymore

```        const user = new SteamUser();
        const community = new SteamCommunity();

        user.logOn({
            accountName: login,
            password: password,
            twoFactorCode: steam_totp.generateAuthCode(shared_secret)
        });

        user.on('loggedOn', () => {
            console.log('Logged in into', login);
        });

        user.on('error', (err) => {
            console.error(err);
        });

        user.on('webSession', (sessionID, cookies) => {
            community.setCookies(cookies);
            accounts[login].community = community; // Store the community object in the account
        });```

**Comment by g0dzcsgo** [comment] 2023-10-19 19:08
> I was trying to solve it myself for 3 hourse until I read previous issues and replaced authentication with most recent version of steam-user.
> 
> community.login() does not work anymore
> 
> ```
> const {shared_secret, password} = accounts[login];
> const user = new SteamUser();
> accounts[login].user = user; // Store user instance in accounts
> 
> user.logOn({
>   accountName: login,
>   password: password,
>   twoFactorCode: steamTotp.generateAuthCode(shared_secret),
> });
> 
> await new Promise((resolve) => {
>   user.once('loggedOn', () => {
>     console.log('Logged in into', login);
>     resolve();
>   });
> });
> 
> user.on('webSession', (sessionID, cookies) => {
>   const community = new SteamCommunity();
>   community.setCookies(cookies);
>   accounts[login].community = community;
> 
>   result.push({
>     login,
>     steamCookies: cookies,
> });
> ```

I tried your method, but still when using the sessionID and cookies returned from listening to "webSession" and passing those to the httpRequestPost still yields an error saying: You must be logged in to perform that action.

**Comment by zyoi** [comment] 2023-10-19 20:27
Does the steam-user version is 5?

**Comment by DoctorMcKay** [comment] 2023-10-19 23:22
Duplicate of #321

**Closed by DoctorMcKay** 2023-10-19 23:22 UTC
