### ISSUE TITLE
get account data error

### ISSUE THREAD

**Issue by BoyKaYK** [DoctorMcKay/node-steamcommunity#322] opened 2023-10-19 06:56 UTC
Hello, today i get a 'get account data error' `typeerror:cannot read properties of null (reading 0)` when i trying to ligin to account with my steam bot.
Is it any new changes from Steam or just my problem? I tried it 2 days ago and it worked fine and i didn't make any changes form that time.
![9ce15269-e49e-4406-92bc-242606fcbb93](https://github.com/DoctorMcKay/node-steam-user/assets/88595925/4b3a2bf6-6e5a-4c5d-913a-e8a269688344)

**Comment by Shybko** [comment] 2023-10-19 11:42
May be will help comment https://github.com/DoctorMcKay/node-steamcommunity/issues/321#issuecomment-1770719801

**Comment by DoctorMcKay** [comment] 2023-10-19 23:23
Likely duplicate of #321

**Closed by DoctorMcKay** 2023-10-19 23:23 UTC
