### ISSUE TITLE
postUserComment Problem

### ISSUE THREAD

**Issue by NetLuiz** [DoctorMcKay/node-steamcommunity#231] opened 2019-09-29 19:15 UTC
When I try to leave comment i get the error below:
The settings on this account do not allow you to add comments.
I tried to do this on multiple users and none of them worked. I enabled comments from Privacy Settings.
My code:
```javascript
client.on("friendMessage", function(steamID) {
  community.postUserComment(steamID, "Test", function (err) {
    console.log(err);
  })
})

**Comment by DoctorMcKay** [comment] 2019-09-29 21:59
Duplicate of #217

**Closed by DoctorMcKay** 2019-09-29 21:59 UTC
Labels: duplicate
